// Generated by scripts/stamp-build.py; do not edit.
enum BuildIdentity { static let value = "mox-fd1de201a78e454351548ba4d47c92a0ffb6c49b7ed8eaf3fb8cde8e35e50d99"; static let productVersion = "0.1.0" }
