// Generated by scripts/stamp-build.py; do not edit.
enum BuildIdentity { static let value = "mox-b9c54a26238f40e2587964d5907f876429b083417db18128330fd43ed76920e5"; static let productVersion = "0.1.0" }
