// Generated by scripts/stamp-build.py; do not edit.
enum BuildIdentity { static let value = "mox-52538e001a5ac0aa5ea32cad7001fa82b8bae110fa72459615230f18c690dc94"; static let productVersion = "0.1.0" }
