#!/bin/bash
set -euo pipefail
milestone="${MOX_BUILD_MILESTONE:-m2}"
source_dir="$SRCROOT/.build/${milestone}-worker/$CONFIGURATION"
helpers="$TARGET_BUILD_DIR/$CONTENTS_FOLDER_PATH/Helpers"
target_dir="$helpers/MoxWorker.app/Contents"
if [[ ! -f "$source_dir/mox" || ! -f "$source_dir/mlx.metallib" ]]; then
  echo 'Missing worker resources; run the matching milestone build script first.' >&2
  exit 1
fi
mkdir -p "$target_dir/MacOS" "$target_dir/Resources"
cp "$source_dir/mox" "$target_dir/MacOS/mox"
for bundle in "$source_dir"/*.bundle; do ditto "$bundle" "$target_dir/Resources/$(basename "$bundle")"; done
ditto "$source_dir/licenses" "$target_dir/Resources/licenses"
cat > "$target_dir/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
<key>CFBundleIdentifier</key><string>dev.mox.worker</string>
<key>CFBundleExecutable</key><string>mox</string>
<key>CFBundlePackageType</key><string>APPL</string>
<key>CFBundleVersion</key><string>1</string>
<key>LSBackgroundOnly</key><true/>
</dict></plist>
PLIST
# Clean only files previously generated by this phase at the incorrect code location.
for file in "$helpers/mox" "$helpers/mlx.metallib"; do if [[ -f "$file" ]]; then rm "$file"; fi; done
if [[ -d "$helpers/licenses" ]]; then rm -r "$helpers/licenses"; fi
for bundle in "$helpers"/*.bundle; do if [[ -d "$bundle" ]]; then rm -r "$bundle"; fi; done
/usr/bin/codesign --force --sign - "$helpers/MoxWorker.app"
