#!/usr/bin/env python3
"""Give the app and worker the same deterministic production-source identity."""
from hashlib import sha256
from pathlib import Path
import sys

root = Path(__file__).resolve().parent.parent
output = root / 'Sources/MoxProtocol/BuildIdentity.swift'
paths = set((root / 'Sources').rglob('*.swift')) | set((root / 'App').rglob('*.swift'))
paths.update(root / name for name in ('Package.swift', 'Package.resolved', 'VERSION', 'scripts/build.sh', 'scripts/prepare-build.py', 'scripts/collect-licenses.py', 'scripts/check-toolchain.sh', 'scripts/embed-worker.sh', 'scripts/generate-xcode-project.py', 'scripts/stamp-build.py'))
paths.discard(output)
digest = sha256()
for path in sorted(paths):
    digest.update(str(path.relative_to(root)).encode() + b'\0' + path.read_bytes() + b'\0')
version = (root / 'VERSION').read_text().strip()
import re
if not re.fullmatch(r'[0-9]+\.[0-9]+\.[0-9]+', version):
    sys.exit('VERSION must contain a semantic product version.')
identity = 'mox-' + digest.hexdigest()
content = '// Generated by scripts/stamp-build.py; do not edit.\n' + 'enum BuildIdentity { static let value = "' + identity + '"; static let productVersion = "' + version + '" }\n'
if '--check' in sys.argv:
    if not output.exists() or output.read_text() != content:
        sys.exit('Worker sources changed; run scripts/build.sh for this configuration.')
    print(identity)
    sys.exit(0)
if not output.exists() or output.read_text() != content:
    output.write_text(content)
print(identity)
