#!/usr/bin/env python3
"""Give the app and worker the same deterministic production-source identity."""
from hashlib import sha256
from pathlib import Path
import os

root = Path(__file__).resolve().parent.parent
output = root / 'Sources/MoxProtocol/BuildIdentity.swift'
paths = set((root / 'Sources').rglob('*.swift')) | set((root / 'App').rglob('*.swift'))
paths.update(root / name for name in ('Package.swift', 'Package.resolved', 'scripts/build-m3.sh', 'scripts/build-m4.sh', 'scripts/embed-worker.sh', 'scripts/generate-xcode-project.py', 'scripts/stamp-m3-build.py'))
paths.discard(output)
digest = sha256()
for path in sorted(paths):
    digest.update(str(path.relative_to(root)).encode() + b'\0' + path.read_bytes() + b'\0')
identity = 'mox-' + os.environ.get('MOX_BUILD_MILESTONE', 'm3') + '-' + digest.hexdigest()
content = '// Generated by scripts/stamp-m3-build.py; do not edit.\n' + 'enum BuildIdentity { static let value = "' + identity + '" }\n'
if not output.exists() or output.read_text() != content:
    output.write_text(content)
print(identity)
