#!/usr/bin/env python3
"""Give the app and worker the same deterministic production-source identity."""
from hashlib import sha256
from pathlib import Path

root = Path(__file__).resolve().parent.parent
output = root / 'Sources/MoxProtocol/BuildIdentity.swift'
paths = set((root / 'Sources').rglob('*.swift')) | set((root / 'App').rglob('*.swift'))
paths.update(root / name for name in ('Package.swift', 'Package.resolved', 'scripts/build-m2.sh', 'scripts/embed-worker.sh', 'scripts/generate-xcode-project.py', 'scripts/stamp-m2-build.py'))
paths.discard(output)
digest = sha256()
for path in sorted(paths):
    digest.update(str(path.relative_to(root)).encode() + b'\0' + path.read_bytes() + b'\0')
identity = 'mox-m2-' + digest.hexdigest()
content = '// Generated by scripts/stamp-m2-build.py; do not edit.\n' + 'enum BuildIdentity { static let value = "' + identity + '" }\n'
if not output.exists() or output.read_text() != content:
    output.write_text(content)
print(identity)
